version: 2
jobs:
  emulator-build-test-publish:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Update Submodules
          command: |
            git submodule update --init --recursive
      - setup_remote_docker
      - run:
          name: Emulator Tests
          command: |
            pushd ./scripts/emulator
            set +e
            docker-compose up --build firmware-unit
            UNIT_RESULTS="$?"
            docker-compose up --build python-keepkey
            TEST_RESULTS="$?"
            set -e
            docker cp "$(docker-compose ps -q firmware-unit)":/kkemu/test-reports/. ../../test-reports/
            docker cp "$(docker-compose ps -q python-keepkey)":/kkemu/test-reports/. ../../test-reports/
            popd
            (exit $UNIT_RESULTS) || (exit $TEST_RESULTS)
      - store_test_results:
          path: test-reports
      - deploy:
          name: Publish Emulator
          command: |
            docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PWD"
            docker tag kktech/kkemu:latest kktech/kkemu:$CIRCLE_SHA1
            docker tag kktech/kkemu:latest kktech/kkemu:$CIRCLE_BRANCH
            docker push kktech/kkemu:$CIRCLE_SHA1
            docker push kktech/kkemu:$CIRCLE_BRANCH
workflows:
  version: 2
  emulator:
    jobs:
      - emulator-build-test-publish

