version: 2.1
jobs:
  emulator-build-test-publish:
    docker:
      - image: circleci/python:2.7.15
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Update Submodules
          command: |
            git submodule update --init --recursive
      - setup_remote_docker
      - run:
          name: Build Emulator
          command: |
            docker build -t kktech/kkemu:$CIRCLE_SHA1 . -f ./scripts/emulator/Dockerfile
      - run:
          name: Docker Create
          command: |
            docker create -v /kkemu --name dummy kktech/kkemu:$CIRCLE_SHA1 /bin/true
      - run:
          name: Bridge Unittests
          command: |
            sudo pip install pipenv
            #docker run -p 5000:5000 -d --volumes-from dummy kktech/kkemu:$CIRCLE_SHA1
            #mkdir -p test-reports/bridgetests
            cd ./scripts/emulator
            set +e
            docker-compose up --build bridge-tests
            BRIDGE_RESULTS="$?"

            #pip install --user pytest
            #python -m pytest bridge_test.py --junitxml=../../test-reports/bridgetests/junit.xml
            #TEST_STATUS="$?"
            set -e
            exit $TEST_STATUS
      - run:
          name: Emulator Tests
          command: |
            cd ./scripts/emulator
            set +e
            docker-compose up --build firmware-unit
            UNIT_RESULTS="$?"
            docker-compose up --build python-keepkey
            TEST_RESULTS="$?"
            set -e
            (exit $UNIT_RESULTS) || (exit $TEST_RESULTS)
      - store_test_results:
          path: scripts/emulator/test-reports
      - deploy:
          name: Publish Emulator
          command: |
            docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PWD"
            docker tag kktech/kkemu:latest kktech/kkemu:$CIRCLE_SHA1
            docker tag kktech/kkemu:latest kktech/kkemu:$CIRCLE_BRANCH
            docker push kktech/kkemu:$CIRCLE_SHA1
            docker push kktech/kkemu:$CIRCLE_BRANCH
workflows:
  version: 2
  emulator:
    jobs:
      - emulator-build-test-publish

