version: 2.1
jobs:
  emulator-build-test:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run:
          name: Update Submodules
          command: |
            git submodule update --init --recursive
      - setup_remote_docker
      - run:
          name: Build Emulator
          command: |
            docker build -t kktech/kkemu:$CIRCLE_SHA1 . -f ./scripts/emulator/Dockerfile
      - run:
          name: Docker Create
          command: |
            docker create -v /kkemu --name dummy kktech/kkemu:$CIRCLE_SHA1 /bin/true
      - run:
          name: Bridge Unittests
          command: |
            mkdir -p test-reports/bridgetests
            cd scripts/emulator
            set +e
            pip install --user pytest
            python -m pytest bridge_test.py --junitxml=../../test-reports/bridgetests/junit.xml
            TEST_STATUS="$?"
            set -e
            exit $TEST_STATUS
      - run:
          name: Emulator Tests
          command: |
            pushd ./scripts/emulator
            set +e
            docker-compose up --build firmware-unit
            UNIT_RESULTS="$?"
            docker-compose up --build python-keepkey
            TEST_RESULTS="$?"
            set -e
            docker cp "$(docker-compose ps -q firmware-unit)":/kkemu/test-reports/. ../../test-reports/
            docker cp "$(docker-compose ps -q python-keepkey)":/kkemu/test-reports/. ../../test-reports/
            popd
            (exit $UNIT_RESULTS) && (exit $TEST_RESULTS)
      - store_test_results:
          path: test-reports
workflows:
  version: 2
  emulator:
    jobs:
      - emulator-build-test

